#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Digging the digital
title: Digging the digital
# Short bio or description (displayed in the header)
description: Vol blogdrift.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/dtd-avatar.png

#Microformats info
mf-avatar: https://en.gravatar.com/userimage/430112/485038288f32582f20027a121f3fd538.jpg?size=200

#Author and h-card information
author: Frank Meeuwsen
email: frank@incredibleadventure.nl
nickname: punkey
words: Blog on

#Timezone because NL
timezone: Europe/Amsterdam

# Github repositories
github_user: frankmeeuwsen
github_repo_url: https://github.com/frankmeeuwsen/DTD-Blog/

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /:title/

# Enables incremental build when I work local. 
incremental: true

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins_dir:
#  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
    - gulpfile.js
    - node_modules
    - config.codekit3
    - .sass-cache

include: [.well-known, index.html]

keep_files: [images, media, files]